.PHONY: clean All

All:
	@echo "----------Building project:[ GameFontTool - DynamicLibrary ]----------"
	@"$(MAKE)" -f  "GameFontTool.mk"
clean:
	@echo "----------Cleaning project:[ GameFontTool - DynamicLibrary ]----------"
	@"$(MAKE)" -f  "GameFontTool.mk" clean
